dwarvesf/github-agent

apps/discord-bot/lang/lang.en-GB.json
apps/discord-bot/lang/lang.en-US.json
apps/discord-bot/package-lock.json
apps/discord-bot/package.json
apps/discord-bot/src/commands/chat/access-command.ts
apps/discord-bot/src/commands/chat/index.ts
apps/discord-bot/src/commands/metadata.ts
apps/discord-bot/src/events/index.ts
apps/discord-bot/src/events/modal-handler.ts
apps/discord-bot/src/models/bot.ts
apps/discord-bot/src/services/index.ts
apps/discord-bot/src/services/webhook-service.ts
apps/discord-bot/src/start-bot.ts

feature: add webhook, modal component for discord bot

---

apps/discord-bot/README.md
apps/discord-bot/src/services/webhook-service.ts

feat: Update webhooks to send message to channel/user

---

apps/discord-bot/Dockerfile
apps/discord-bot/entrypoint.sh
apps/discord-bot/package.json
docker-compose.yml

feat: Add docker config for discord bot

---

apps/agent/src/lib/github.ts
apps/agent/src/mastra/agents/analyze-github-prs.ts
apps/agent/src/mastra/agents/github-agent.ts
apps/agent/src/mastra/agents/index.ts
apps/agent/src/mastra/index.ts
apps/agent/src/mastra/tools/formatter.ts
apps/agent/src/mastra/tools/github.ts
apps/agent/src/mastra/tools/index.ts
apps/agent/src/mastra/workflows/github-notify-open-prs.ts

feat: list all PRs tool and agent

---

apps/agent/package.json
apps/agent/src/lib/github.ts
apps/agent/src/mastra/agents/github-agent.ts
apps/agent/src/mastra/index.ts
apps/agent/src/mastra/tools/datetime.ts
apps/agent/src/mastra/tools/github.ts
apps/agent/src/mastra/tools/index.ts
apps/agent/src/mastra/workflows/github-notify-developer-about-pr-status.ts
apps/agent/src/mastra/workflows/github-send-today-list-PRs-to-discord.ts
apps/agent/src/mastra/workflows/index.ts
apps/agent/src/utils/datetime.ts

feat: add date range filter for list PRs

---

apps/agent/src/lib/github.ts
apps/agent/src/lib/type.d.ts
apps/agent/src/mastra/agents/github-agent.ts
apps/agent/src/mastra/tools/github.ts
apps/agent/src/mastra/workflows/github-notify-developer-about-pr-status.ts
apps/agent/src/mastra/workflows/github-send-today-list-PRs-to-discord.ts

feat: add ability to list commits for agent

---

apps/agent/src/mastra/agents/github-agent.ts
apps/agent/src/mastra/tools/github.ts
apps/agent/src/utils/array.ts
apps/agent/src/utils/string.ts
apps/discord-bot/lang/lang.en-GB.json
apps/discord-bot/lang/lang.en-US.json
apps/discord-bot/src/commands/args.ts
apps/discord-bot/src/commands/chat/ask-command.ts
apps/discord-bot/src/commands/metadata.ts

feat: sum user activities

---

apps/agent/src/mastra/tools/github.ts
apps/discord-bot/src/commands/chat/ask-command.ts
apps/discord-bot/src/commands/common.ts
apps/discord-bot/src/commands/index.ts
apps/discord-bot/src/services/webhook-service.ts

Feat: discord bot github_id, discord_id mapping

---

apps/agent/src/mastra/workflows/github-send-today-list-PRs-to-discord.ts
apps/agent/src/utils/datetime.ts

feat: polish today summary workflow

---

.github/actions/setup-env/action.yml
.github/workflows/checks.yml
apps/agent/package.json
apps/agent/src/constants/discord.ts
apps/agent/src/db/connection.ts
apps/agent/src/utils/__tests__/string.test.ts
apps/agent/src/utils/string.ts
package.json
pnpm-lock.yaml
vitest.config.mts
vitest.setup.ts

- https://www.notion.so/dwarves/Add-unit-testing-with-vitest-1c064b29b84c80aeb8e8ddd14ca7356e?pvs=4

test: add vitest

---

apps/agent/src/mastra/workflows/github-notify-inactive-prs.ts

chore: add condition to send inactive PRs

---

apps/agent/src/lib/github.ts
apps/agent/src/lib/type.d.ts
apps/agent/src/mastra/workflows/github-notify-developer-about-pr-status.ts

- https://www.notion.so/dwarves/Alerts-for-approved-PRs-that-haven-t-been-merged-yet-1c164b29b84c8084a35df0e2ac185c5d
- PR's not already merged
- PR's not marked as work in progress
- PR has at least one approved review
- No reviews have been dismissed after the most recent approval

feat: approved PRs not merged notify

---

apps/agent/src/mastra/workflows/github-notify-inactive-prs.ts
apps/agent/src/utils/datetime.ts
apps/agent/src/utils/string.ts

fix: snapshot text and truncate long PR title

---

apps/agent/src/mastra/workflows/github-notify-inactive-prs.ts

- 
- Chunk the messages for 5 bullets message per field (to avoid limit field value length)
- Update fields value display

chore: update notify inactive PR msg

---

apps/agent/src/mastra/workflows/github-notify-inactive-prs.ts

- Author has redundant symbol on inactive PRs workflows need to be removed

fix: redundant symbol

---

apps/agent/entrypoint.sh

- unable to run prod due to lack of prisma error

fix(agent): prisma type error

---

apps/agent/src/mastra/index.ts
apps/agent/src/mastra/workflows/github-notify-reviewers.ts
apps/agent/src/mastra/workflows/index.ts

[Ticket](https://www.notion.so/dwarves/GitHub-agent-1a664b29b84c80568524fa8d6eb2ded8?p=1c164b29b84c807e9e67cd3a542d4902&pm=s)

feat: notify assigned reviewer

---

apps/agent/entrypoint.sh
apps/agent/src/db/connection.ts
apps/agent/src/db/event.repository.ts
apps/agent/src/db/index.ts
apps/agent/src/mastra/workflows/github-notify-developer-about-pr-status.ts
apps/agent/src/mastra/workflows/github-notify-inactive-prs.ts
apps/agent/src/mastra/workflows/github-send-today-list-PRs-to-discord.ts

- Update to get prisma generated with edge config

fix: import prisma from edge

---

apps/agent/prisma/migrations/20250414063950_org_repo_schema/migration.sql
apps/agent/prisma/schema.prisma

feat(agent): add db schema for org, repo configs

---

apps/agent/src/db/channel.repository.ts
apps/agent/src/db/event.repository.ts
apps/agent/src/db/index.ts
apps/agent/src/db/member.repository.ts
apps/agent/src/db/organization.repository.ts
apps/agent/src/db/repository.ts
apps/agent/src/lib/discord.ts
apps/agent/src/lib/github.ts
apps/agent/src/lib/notification-embed.ts
apps/agent/src/lib/repository-dm-user.ts
apps/agent/src/lib/type.d.ts
apps/agent/src/mastra/agents/analyze-github-prs.ts
apps/agent/src/mastra/index.ts
apps/agent/src/mastra/tools/github.ts
apps/agent/src/mastra/workflows/github-notify-developer-about-pr-status.ts
apps/agent/src/mastra/workflows/github-notify-inactive-prs.ts
apps/agent/src/mastra/workflows/github-notify-reviewers.ts
apps/agent/src/mastra/workflows/github-send-today-list-PRs-to-discord.ts

*   **Added `ChannelRepository`:** Introduced a new repository class to handle database operations for `Channel` entities, including CRUD operations and methods to fetch channels by organization or unique identifiers.
*   **Added `MemberRepository`:** Created a new class for managing `Member` entities in the database. It provides standard CRUD functions along with methods to retrieve members by platform, GitHub ID, or unique identifiers.
*   **Added `OrganizationRepository`:** Implemented a class dedicated to `Organization` entity database interactions, featuring CRUD operations and a method to find an organization by its unique GitHub name.
*   **Added `Repositories`:** Introduced a repository class to manage `Repository` entities. It includes CRUD operations and specific methods for …

feat: data query for dm workflows

---

apps/agent/src/mastra/workflows/github-send-today-list-PRs-to-discord.ts

- Change daily report flow to use data from database

feat: data query for daily report

---

apps/agent/src/db/channel.repository.ts
apps/agent/src/db/member.repository.ts
apps/agent/src/db/repository.ts
apps/agent/src/lib/github-data-manager.ts
apps/agent/src/lib/github.ts
apps/agent/src/lib/id-mapper.ts
apps/agent/src/mastra/index.ts
apps/agent/src/mastra/tools/formatter.ts
apps/agent/src/mastra/tools/github.ts
apps/agent/src/mastra/workflows/github-notify-developer-about-pr-status.ts
apps/agent/src/mastra/workflows/github-notify-reviewers.ts
apps/agent/src/mastra/workflows/github-send-today-list-PRs-to-discord.ts

- Add DB query for ask command

feat: data query for ask command

---

apps/agent/src/lib/github-data-manager.ts
apps/agent/src/lib/github.ts
apps/agent/src/mastra/agents/github-agent.ts
apps/agent/src/mastra/tools/github.ts
apps/discord-bot/src/commands/chat/ask-command.ts

- Add channel ID on doing ask command task
- Update agent prompt for handling channel id and post processing github id to discord id

fix: channel filtering ask

---

apps/agent/src/mastra/workflows/github-notify-inactive-prs.ts

- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?

feat: data query for inactive prs
